config/routes.rb
Rails.application.routes.draw do
  get 'custom_message/index'
  resource :user, only: [:show, :create]
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   '/callback', to: 'callback#callback'
  post   '/callback/:hash', to: 'callback#callback'

  get '/google_auth/test_create/:bot_id', to: 'google_auth#test_create'


  resources :google_auth, only: [] do
    collection do
      get :callback
      get :redirect
      post :set_token
    end
  end

  namespace :api, format: 'json' do
    resources :bot, except: [:new, :index] do
      resources :messages, only: [:show, :index], param: :lineuser_id do#, shallow: true
        member do
          post :create
          patch :update_name
        end
      end
      resources :lineusers, only: [:show, :index] do
        member do
          patch :switch_close
        end
      end
    end
  end

  constraints(id: /[0-9]+/, bot_id: /[0-9]+/, lineuser_id: /[0-9]+/) do
    resources :bot, except: [:new, :index] do
      member do
        patch :set_images
        post :set_images
      end
      scope module: 'bot' do
        resources :ab_tests do
          member do
            patch :switch_active
          end
        end
        resources :response_data, only: [:index], shallow: true
        resources :reply_actions
        resources :images, only: [:show], shallow: true
        resources :statuses, only: [:create, :destroy, :index], shallow: true do
          member do
            patch :switch_active
          end
        end
        resources :forms do
          member do
            patch :switch_active
            get :edit_flow
          end
          scope module: 'forms' do
            resources :check_notifications, only: [:create, :destroy, :index] do
              member do
                patch :switch_active
              end
            end
          end
          resources :quick_replies, only: [:create, :destroy, :update], shallow: true do
            member do
              patch :text_update
            end
            resources :quick_reply_items, only: [:create, :destroy], shallow: true
          end
        end
        resources :custom_message, only: [:index], shallow: true do
          collection do
            get :search
            post :broadcast
          end
        end
        resources :remind, except: [:new, :show, :index]#, shallow: true
        resources :lineusers, only: [:show, :index, :edit], shallow: true do
          resources :lineuser_statuses, only: [] do
            collection do
              post :create
              patch :update
              delete :destroy
            end
          end
        end
        resources :chat, only: [:show, :index], param: :lineuser_id do#, shallow: true
          member do
            post :push_flex
            post :create
            post :redirect
            patch :update_name
            post :push_image
          end
        end
      end
    end
  end
  root to: 'users#new'
  # match "*path" => "application#render_404", via: :all
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    lt4bytes: true
  validates :password,  presence: true, confirmation: :true, length: { in: 8..32 }, lt4bytes: true
  scope :undeleted, ->{ where(deleted: false) }
  has_many :bots, ->{ where(deleted: false) }
  require "digest/sha2"

  def self.find_with_email_and_pass(email, password)
    self.find_by(email: email, password: Manager.encrypt(password))
  end

  def self.create_with_email_and_pass(email, password)
    user = self.new(
      email: email,
      password: Manager.encrypt(password)
    )
    user.save!
  end

  def self.get_with_email(email)
    self.undeleted.find_by(email: email)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:create, :new]
  def new
    @current_user ? redirect_to(user_url) : @user = User.new
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        puts("created new user")
        flash[:notice] = "新規ユーザーを作成しました"
        format.js { render ajax_redirect_to(root_url) }
      else
        format.js { render partial: 'shared/error_remote', locals: {model: @user} }
      end
    end
  end
  def show
    @bots = Bot.get_plural_with_user_id(@current_user.id)
    @bot = Bot.new
  end
  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/views/users/_error_box.html.slim
- if @user.errors.any?
  - @user.errors.full_messages.each do |message|
    p = message

app/views/users/email_duplication.js.erb
$('.email-duplication-message').html(
  "<%= escape_javascript(render 'error_box') %>"
  );

app/views/users/new.html.slim
section.hero.is-success
  .hero-body
    .container
      h1.title.is-spaced LINE Bot Messaging
      h2.subtitle ラインボットをもっとべんりに、もっとかんたんに
.container
  .columns.is-centered
    .column.is-6
      #top-login-box.box.is-spaced
        label.label.is-large ログイン
        .login-validates.error
        = form_with model: @user, url: login_path, method: :create, data: { parsley_validate: "" }, html: { class: "form" } do |f|
          .field
            .control.has-icons-left.has-icons-right
              = f.text_field :email, placeholder: "メールアドレス", 'data-parsley-type' => "email", class: "input", id: "login-email", type: "email", 'required' => ""
              span.icon.is-small.is-left
                i.fas.fa-envelope
              span.icon.is-small.is-right
                i.fas.fa-check
          .field
            .control.has-icons-left
              = f.password_field :password,  placeholder: "パスワード", class: "input", id: "login-password", 'required' => ""
              span.icon.is-small.is-left
                i.fas.fa-lock
          p.control
            = f.submit "ログイン", class: "button is-success"
            span.button.signup-button 新規登録
#signup-modal.modal
  .modal-background
  .modal-content
    .modal-content-box
      label.label.is-large 新規アカウント登録
      .error-message.error
      = form_with model: @user, url: user_path, data: { parsley_validate: "" }, html: { class: "form" } do |f|
        .field
          .control.has-icons-left.has-icons-right
            = f.text_field :email, placeholder: "メールアドレス",class: "input form-control", 'required' => "", type: "email"
            span.icon.is-small.is-left
              i.fas.fa-envelope
            span.icon.is-small.is-right
              i.fas.fa-check
        .field
          p.control.has-icons-left
            = f.password_field :password,  placeholder: "パスワード", class: "input form-control",'required' => "", 'data-parsley-length'=>"[6, 20]"
            span.icon.is-small.is-left
              i.fas.fa-lock
        .field
          p.control.has-icons-left
            = f.password_field :password_confirmation,  placeholder: "パスワードを再入力", 'data-parsley-equalto' => "#user_password", class: "input form-control", 'required' => ""
            span.icon.is-small.is-left
              i.fas.fa-lock
        p.control
          = f.submit "新規登録", class: "button is-success"
  button.modal-close.is-large aria-label="close"
javascript:
  | Parsley.options.trigger = "keyup focusout change input";

app/views/users/show.html.erb
<div class="columns max-height">
  <div class="column is-2 is-hidden-mobile">
    <div class="side-menu">
      <div class="side-menu-title">
        <span>Botリスト</span>
      </div>
      <div class="side-menu-list-box">
        <% @bots.each do |bot|%>
          <div class="side-menu-list-item">
            <%= link_to "#{bot.name}", bot_path(bot) %>
          </div>
        <% end %>
      </div>
      <div class="centered">
        <%= link_to "ログアウト", logout_path, method: :delete, class: "button", id: "side-logout" %>
      </div>
    </div>
  </div>
  <div class="column is-10">
    <div class="container">
      <div class="level-space">
        <nav class="level">
          <!-- Left side -->
          <div class="level-left">
            <div class="level-item">
              <span class="is-size-3 align-middle">追加済みLINEbot </span>
            </div>
          </div>
          <!-- Right side -->
          <div class="level-right">
            <div class="level-item">
              <button class="button is-info new-bot-button"><i class="fas fa-plus"></i>新規bot登録</button>
              <%= link_to "ログアウト", logout_path, method: :delete, class: "button is-hidden-tablet" %>
            </div>
          </div>
        </nav>
        <hr class="hr" style="margin: 0;">
      </div>
      <table class="table is-fullwidth is-hoverable" id="bot-table">
        <thead>
          <tr>
            <th>bot</th>
            <th>登録日</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% if @bots %>
            <% @bots.each do |bot|%>
              <tr data-href= <%= bot_path(bot) %> >
                <td><%= bot.name %></td>
                <td><%= bot.created_at %></td>
                <td><%= link_to "管理", bot_path(bot) %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="is-centered is-spaced">
        <button class="button is-info new-bot-button"><i class="fas fa-plus"></i> 新規bot登録</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" id="new-bot-modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="modal-content-box">
      <label class="label is-large"> 新規Bot登録</label>
      <%= form_with model: @bot, url: bot_index_path, data: { parsley_validate: "" }, html: { class: "form" }, local: true do |f| %>
        <div class="field">
          <p class="control has-icons-left has-icons-right">
            <%= f.text_field :name, placeholder: "名前", class: "input form-control", 'required' => "" %>
          </p>
        </div>
        <div class="field">
          <p class="control has-icons-left has-icons-right">
            <%= f.text_field :channel_secret, placeholder: "channel_secret", class: "input form-control", 'required' => "" %>
          </p>
        </div>
        <div class="field">
          <p class="control has-icons-left has-icons-right">
            <%= f.text_field :channel_token, placeholder: "channel_token",class: "input form-control", 'required' => "" %>
          </p>
        </div>
        <div class="field">
          <p class="control has-icons-left">
            <%= f.text_field :description, placeholder: "説明(任意)",class: "input form-control" %>
          </p>
        </div>
        <p class="control">
          <%= f.submit "新規登録", class: "button is-success" %>
        </p>
      <% end %>
    </div>
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>
<script type="text/javascript">
  Parsley.options.trigger = "keyup focusout change input";
</script>