config/routes.rb
Rails.application.routes.draw do
  get 'custom_message/index'
  resource :user, only: [:show, :create]
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post   '/callback', to: 'callback#callback'
  post   '/callback/:hash', to: 'callback#callback'

  get '/google_auth/test_create/:bot_id', to: 'google_auth#test_create'


  resources :google_auth, only: [] do
    collection do
      get :callback
      get :redirect
      post :set_token
    end
  end

  namespace :api, format: 'json' do
    resources :bot, except: [:new, :index] do
      resources :messages, only: [:show, :index], param: :lineuser_id do#, shallow: true
        member do
          post :create
          patch :update_name
        end
      end
      resources :lineusers, only: [:show, :index] do
        member do
          patch :switch_close
        end
      end
    end
  end

  constraints(id: /[0-9]+/, bot_id: /[0-9]+/, lineuser_id: /[0-9]+/) do
    resources :bot, except: [:new, :index] do
      member do
        patch :set_images
        post :set_images
      end
      scope module: 'bot' do
        resources :ab_tests do
          member do
            patch :switch_active
          end
        end
        resources :response_data, only: [:index], shallow: true
        resources :reply_actions
        resources :images, only: [:show], shallow: true
        resources :statuses, only: [:create, :destroy, :index], shallow: true do
          member do
            patch :switch_active
          end
        end
        resources :forms do
          member do
            patch :switch_active
            get :edit_flow
          end
          scope module: 'forms' do
            resources :check_notifications, only: [:create, :destroy, :index] do
              member do
                patch :switch_active
              end
            end
          end
          resources :quick_replies, only: [:create, :destroy, :update], shallow: true do
            member do
              patch :text_update
            end
            resources :quick_reply_items, only: [:create, :destroy], shallow: true
          end
        end
        resources :custom_message, only: [:index], shallow: true do
          collection do
            get :search
            post :broadcast
          end
        end
        resources :remind, except: [:new, :show, :index]#, shallow: true
        resources :lineusers, only: [:show, :index, :edit], shallow: true do
          resources :lineuser_statuses, only: [] do
            collection do
              post :create
              patch :update
              delete :destroy
            end
          end
        end
        resources :chat, only: [:show, :index], param: :lineuser_id do#, shallow: true
          member do
            post :push_flex
            post :create
            post :redirect
            patch :update_name
            post :push_image
          end
        end
      end
    end
  end
  root to: 'users#new'
  # match "*path" => "application#render_404", via: :all
end

app/models/bot/ab_test_form.rb
class Bot::AbTestForm < ApplicationRecord
  belongs_to :ab_test
  belongs_to :form
end

app/models/bot/check_notification_quick_reply.rb
class Bot::CheckNotificationQuickReply < ApplicationRecord
  belongs_to :check_notification
  belongs_to :quick_reply
end

app/models/bot/slack_api_set.rb
class Bot::SlackApiSet < ApplicationRecord
  belongs_to :bot
  validates :webhook_url, lt4bytes: true
  validates :bot_id, numericality: true

  def self.update_or_create(bot, webhook_url)
    slack_api_set = self.find_or_initialize_by(bot_id: bot.id)
    slack_api_set.update_attributes!(webhook_url: webhook_url)
  end

end

app/controllers/bot/ab_tests_controller.rb
class Bot::AbTestsController < ApplicationController
  before_action :set_bot
  layout 'bot_layout'

  def index
    @forms = @bot.forms
    @ab_tests = @bot.ab_tests.where(is_active: false)
    @active_ab_test = @bot.ab_tests.includes(:forms).includes(:forms => :converted_lineusers, :forms => :session_lineusers).find_by(is_active: true)
    @ab_test = @bot.ab_tests.new
  end

  def show

  end

  def create
    ActiveRecord::Base.transaction do
      ab_test = @bot.ab_tests.new(ab_test_params)
      ab_test.save!
      Bot::AbTest.associate_forms(ab_test, ab_test_forms_params[:ab_test_forms_attributes][:form_ids])
    end
    redirect_to bot_ab_tests_path(@bot.id)
  rescue => e
    Rails.logger.fatal e.message
    redirect_to bot_ab_tests_path(@bot.id), alert: "作成に失敗しました"
  end

  def destroy
    ab_test = @bot.ab_tests.get(params[:id])
    ab_test.destroy!
    redirect_to bot_ab_tests_path(@bot.id)
  end

  def switch_active
    ab_test = @bot.ab_tests.get(params[:id])
    ActiveRecord::Base.transaction do
      ab_test.switch_active
    end
    redirect_to bot_ab_tests_path(@bot.id)
  rescue => e
    Rails.logger.fatal e.message
    redirect_to bot_ab_tests_path(@bot.id), alert: "エラーが発生しました"
  end

  private
  def set_bot
    @bot = current_user.bots.get(params[:bot_id])
  end
  def ab_test_params
    params.require(:bot_ab_test).permit(:name)
  end
  def ab_test_forms_params
    params.require(:bot_ab_test).permit(ab_test_forms_attributes: {form_ids: []} )
  end
end

app/controllers/bot/chat_controller.rb
class Bot::ChatController < ApplicationController
  before_action :check_auth, :set_bot

  def index
    @bot = current_user.bots.includes(:lineusers => :messages).get(params[:bot_id])
    render :show
  end

  def show
    #トーク履歴が多いと重くなりそう
    @bot = current_user.bots.get(params[:bot_id])
    @lineuser = @bot.lineusers.get(params[:lineuser_id])
    template_list = @bot.quick_replies.includes(:form).where("forms.is_template = true").pluck(:name, :id)
    @quick_reply_list = template_list # + @bot.forms.active.quick_replies.pluck(:name, :id)
    Manager.update_lineuser_profile(@bot, @lineuser.uid, false)
    @status_array = @bot.get_status_array
  end

  def redirect
    @bot = current_user.bots.includes(:lineusers).includes(:lineusers => :lastmessage).get(params[:bot_id])
    #:replied に返信済みユーザーが, :not_repliedに未返信ユーザーが配列で入る
    @lineusers = Manager.sort_by_is_replied(@bot.lineusers)
    @lineuser = @bot.lineusers.includes(:messages, :response_data).get(params[:lineuser_id])
    @quick_reply_list = @bot.quick_replies.where(is_normal_message: false)
    @value = {message: params[:redirect_message], name: params[:redirect_name]}
    render :show
  end

  def create
    msg = params[:message]
    Manager.push(@bot.lineusers.get(params[:lineuser_id]), msg)
    redirect_to bot_chat_path(params[:bot_id], params[:lineuser_id])
  end

  def update_name
    @lineuser = @bot.lineusers.get(params[:lineuser_id])
    Manager.save_or_refresh_name(@bot, @lineuser, params[:name])
    redirect_to bot_chat_path(params[:bot_id], params[:lineuser_id])
  end

  def push_flex
    lineuser = @bot.lineusers.get(params[:lineuser_id])
    quick_reply = @bot.quick_replies.get(params[:quick_reply][:id])
    Manager.push_flex(lineuser, quick_reply)
    redirect_to bot_chat_path(@bot.id, lineuser.id)
  end

  def push_image
    stock_image = @bot.stock_images.find_by(image_param)
    lineuser = @bot.lineusers.get(params[:lineuser_id])
    ActiveRecord::Base.transaction do
      Manager.push_image(lineuser, stock_image)
    end
    redirect_to bot_chat_path(@bot.id, lineuser.id)
  rescue => e
    Rails.logger.fatal e.message
    redirect_to bot_chat_path(@bot.id, lineuser.id), alert: "エラーが発生しました"
  end

  private
    def check_auth
      return if !params[:id]
      if Lineuser.get(params[:lineuser_id]).bot.user_id != current_user.id
        render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
      end
    end

    def set_bot
      @bot = current_user.bots.get(params[:bot_id])
    end

    def image_param
      params.require(:stock_image).permit(:id)
    end

end

app/controllers/bot/custom_message_controller.rb
class Bot::CustomMessageController < ApplicationController
  layout 'bot_layout'
  def index
    @bot = current_user.bots.includes(:reminds, :lineusers).get(params[:bot_id])
    @lineusers = @bot.lineusers.includes(:lastmessage).order("messages.created_at desc").limit(50)
    @search = LineuserSearch.new
    @status_array = @bot.get_status_array
    #render json: @users.select("id").map { |e| e.id  }.to_json unless params[:q].blank?
  end

  def search
    @bot = Bot.includes(:reminds, :lineusers).get(params[:bot_id])
    @status_array = @bot.get_status_array
    @search = LineuserSearch.new(search_params)
    if search_params.permitted?
      @lineusers = Lineuser.custom_search(@bot.lineusers, search_params)
    end
    @lineusers = @lineusers.includes(:lastmessage).order("messages.created_at desc")
    render :index
  end

  def broadcast
    lineusers = current_user.bots.get(params[:bot_id]).lineusers.where(id: broadcast_params[:lineusers])
    Manager.push_multicast(lineusers, broadcast_params[:text])
    redirect_to bot_custom_message_index_path(params[:bot_id]), notice: "一斉送信を実行しました"
  end

  private
    def search_params
      params.require(:lineuser_search).permit(:name, :convert_time_from, :convert_time_to, :session_time_from, :session_time_to, :messages_created_at_from, :messages_created_at_to, :limit, :status_id)
    end
    def broadcast_params
      params.require(:broadcast).permit(:text, lineusers: [])
    end
end

app/controllers/bot/forms/check_notifications_controller.rb
class Bot::Forms::CheckNotificationsController < ApplicationController
  before_action :set_bot_form
  layout 'bot_layout'

  def index
    @check_notifications = @bot.check_notifications.includes(:quick_replies)
    @new_check_notification = @bot.check_notifications.new
    @quick_replies = @form.quick_replies
  end

  def create
    ActiveRecord::Base.transaction do
      check_notification = @bot.check_notifications.new(check_notification_params)
      check_notification.save!
      Bot::CheckNotification.associate_quick_replies(check_notification, check_notification_quick_replies_params[:check_notification_quick_replies_attributes][:quick_reply_ids], @form)
    end
    redirect_to bot_form_check_notifications_path(@bot.id, @form)
  rescue => e
    Rails.logger.fatal e.message
    redirect_to bot_form_check_notifications_path(@bot.id, @form), alert: "作成に失敗しました"
  end

  def destroy
    check_notification = @bot.check_notifications.get(params[:id])
    check_notification.destroy!
    redirect_to bot_form_check_notifications_path(@bot.id, @form)
  end

  def switch_active
    check_notification = @bot.check_notifications.get(params[:id])
    ActiveRecord::Base.transaction do
      check_notification.switch_active
    end
    redirect_to bot_form_check_notifications_path(@bot.id, @form)
  rescue => e
    Rails.logger.fatal e.message
    redirect_to bot_form_check_notifications_path(@bot.id, @form), alert: "エラーが発生しました"
  end

  private
  def set_bot_form
    @bot = current_user.bots.get(params[:bot_id])
    @form = @bot.forms.get(params[:form_id])
  end
  def check_notification_params
    params.require(:bot_check_notification).permit(:name, :is_active)
  end
  def check_notification_quick_replies_params
    params.require(:bot_check_notification).permit(check_notification_quick_replies_attributes: {quick_reply_ids: []} )
  end
end

app/controllers/bot/forms_controller.rb
class Bot::FormsController < ApplicationController
  before_action :check_auth, :set_bot
  layout 'bot_layout'

  def index
    @bot = current_user.bots.get(params[:bot_id])
    @forms = @bot.forms.includes(:converted_lineusers, :session_lineusers).where(is_active: false)
    @active_form = @bot.forms.includes(:converted_lineusers, :session_lineusers).find_by(is_active: true)
    @active_ab_test = @bot.ab_tests.find_by(is_active: true)
    @new_form = Form.new
  end

  def show
    @form = Form.includes(:quick_replies).get(params[:id])
    bot_id = @form.bot.id
    @bot = current_user.bots.includes(:google_api_set).get(bot_id)
    @quick_replies = @form.quick_replies.includes(:quick_reply_items)
    @quick_reply = @form.quick_replies.new
    @days = ["日", "月", "火", "水", "木", "金", "土"]
  end

  def edit_flow
    @form = Form.includes(:quick_replies).get(params[:id])
    bot_id = @form.bot.id
    @bot = Bot.includes(:google_api_set).get(bot_id)
    @quick_replies = @form.quick_replies.includes(:quick_reply_items)
    @quick_replies_select_array = QuickReply.select_array(@quick_replies)
  end

  def create
    bot = Bot.get(params[:bot_id])
    form = bot.forms.new(form_params)
    form.save!
    redirect_to bot_forms_url
  end

  def switch_active
    form = Form.get(params[:id])
    form.switch_active_do(form)
    redirect_to bot_form_url
  end

  def update
    form = Form.get(params[:id])
    form.update_attributes!(form_params)
  end

  private
    def check_auth
      return if !params[:id]
      if Form.get(params[:id]).bot.user_id != @current_user.id
        render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
      end
    end
    def form_params
      params.require(:form).permit(:name, :describe_text, :first_reply_id)
    end
    def set_bot
      @bot = current_user.bots.get(params[:bot_id])
    end
end

app/controllers/bot/images_controller.rb
class Bot::ImagesController < ApplicationController
  before_action :check_auth

  def show
    message = Message.get(params[:id])
    response = Manager.get_img_binary(message)
    if response.class == Net::HTTPOK
      send_data response.body, type: 'image/jpeg', disposition: 'inline'
    else
      render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
    end
  end

  private
    def check_auth
      return if !params[:id]
      if Message.get(params[:id]).lineuser.bot.user_id != @current_user.id
        render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
      end
    end
end

app/controllers/bot/lineuser_statuses_controller.rb
class Bot::LineuserStatusesController < ApplicationController
  before_action :check_auth

  def create
    lineuser = Lineuser.get(params[:lineuser_id])
    Bot::LineuserStatus.create_or_update(lineuser_status_params, lineuser)
  end

  def update
    lineuser = Lineuser.get(params[:lineuser_id])
    lineuser.lineuser_status.update_attributes!(lineuser_status_params)
  end

  def destroy

  end

  private
  def lineuser_status_params
    params.require(:bot_lineuser_status).permit(:status_id)
  end
  def check_auth
    return if !lineuser_status_params[:status_id].present?
    if Lineuser.get(params[:lineuser_id]).bot.user_id != current_user.id
      render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
    end
  end
end

app/controllers/bot/lineusers_controller.rb
class Bot::LineusersController < ApplicationController
  layout 'bot_layout'
  def index
    @bot = current_user.bots.get(params[:bot_id])
    # @quick_reply_list = @bot.quick_replies.where(is_normal_message: false)
    @lineusers = @bot.lineusers.get_open_users
    @lineusers = @lineusers.includes(:lastmessage, :quick_reply, :converted_lineuser, :lineuser_status).order("messages.created_at desc").limit(30)
    @status_array = @bot.get_status_array
  end
end

app/controllers/bot/quick_replies_controller.rb
class Bot::QuickRepliesController < ApplicationController
  before_action :check_auth, :set_bot
  def index
    @quick_replies = @bot.quick_replies.includes(:quick_reply_items)
    @quick_reply = QuickReply.new
  end

  def show
    @quick_reply = QuickReply.includes(:quick_reply_items).get(params[:id])
  end

  def new
    @quick_reply = QuickReply.new
  end

  def create
    ActiveRecord::Base.transaction do
      QuickReply.optional_create(params[:form_id], quick_reply_params, quick_reply_schedule_params)
    end
    redirect_to bot_form_url(@bot.id, params[:form_id])
  rescue => e
    flash[:notice] = e.message
    redirect_to bot_form_url(@bot.id, params[:form_id])
  end

  def destroy
    quick_reply = QuickReply.get(params[:id])
    ActiveRecord::Base.transaction do
      quick_reply.relational_delete
    end
    redirect_to bot_form_url(@bot.id, quick_reply.form.id)
  end

  def update
    quick_reply = QuickReply.get(params[:id])
    ActiveRecord::Base.transaction do
      quick_reply.update_attributes!(quick_reply_flow_params)
      QuickReplyItem.update_nexts(items_flow_params)
    end
  rescue => e
    flash[:notice] = e.message
    redirect_to edit_flow_bot_form_url(@bot.id, quick_reply.form.id)
  end

  def text_update
    quick_reply = QuickReply.get(params[:id])
    quick_reply.update_attributes!(quick_reply_update_params)
    redirect_to bot_form_url(@bot.id, quick_reply.form.id)
  end

  private
    def check_auth
      return if !params[:id]
      if QuickReply.get(params[:id]).form.bot.user_id != @current_user.id
        render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
      end
    end
    def quick_reply_params
      params.require(:quick_reply).permit(:name, :text, :reply_type)
    end
    def quick_reply_update_params
      params.require(:quick_reply).permit(:name, :text)
    end
    def quick_reply_schedule_params
      params.require(:quick_reply).permit(:summary, :duration_days, :duration_num, :start_num, :term_num, :permission_count, available_day: %i(0 1 2 3 4 5 6))
    end
    def quick_reply_flow_params
      params.require(:quick_reply).permit(:next_reply_id)
    end
    def items_flow_params
      params.require(:quick_reply).permit(quick_reply_items: :next_reply_id)[:quick_reply_items]
    end
    def set_bot
      if params[:bot_id].present?
        @bot = current_user.bots.get(params[:bot_id])
      else
        @bot = current_user.bots.joins({:forms => :quick_replies}).find_by(quick_replies: {id: params[:id]})
      end
    end
end

app/views/bot/chat/sample.html.slim
- if 1 > 0
  p sample

= form_tag root_path method: :post do
  = text_field_tag :message, "", placeholder: "メッセージ"
  = button_tag '<i class="far fa-paper-plane"></i>'.html_safe, :type => "submit", class: "button"

.container
  .box
    = form_with model: post, url: root_path, local: true, method: :create, html: { class: "form" } do |f|
      = f.text_field :message, placeholder: "メッセージ"
      = f.submit '<i class="far fa-paper-plane"></i>'.html_safe, :type => "submit", class: "button"
- str = "abcde"
- if str == "abcde"
  p = str

app/views/bot/chat/show.html.slim
== render 'shared/flash'
#app
  .columns.max-height
    .column.is-3.side-menu.is-hidden-mobile
      = link_to '<i class="far fa-arrow-alt-circle-left"></i>'.html_safe, bot_lineusers_path(@bot), class: "is-size-2"
      = @bot.name
      form.name-form data-parsley-validate="" method="get" data-remote="true" style="margin: 0.5em 0;" v-bind:action="`/bot/${bot_id}/lineusers`" @submit.prevent="fetchLineusers"
        input.input id="search_name" name="name" type="search" v-model="searchName" placeholder="名前" style="width: initial;"
        button.button.is-info.submit-message type="submit" 検索
      .field
        p.control
          .select
            / = select_tag @status_array, {:prompt => "未選択"}, {"v-model"=>"status_select"}
            = select :status, :name, ([["ステータスを選択", 0]] + @status_array), {}, {"v-model"=>"status_select", "v-on:change"=>"fetchLineusers()"}
            / = select_tag 'status[id]', options_from_collection_for_select(@status_array, :id, :name)
      .tabs.is-centered.is-boxed#tabs
        ul
          li data-tab="1" v-on:click="switchTab(1)" v-bind:class="{'is-active': isActive == 1}"
            a
              span 未返信
          li data-tab="2" v-on:click="switchTab(2)" v-bind:class="{'is-active': isActive == 2}"
            a
              span 返信済み
      #tab-content.overflow
        .form-tab v-show="isActive == 1"
          .users-list
            .users-box
              .user-box v-for="lineuser in lineusers" v-if="lineuser.lastmessage.to_bot == true" v-bind:class="{'is-active': lineuser_id == lineuser.id}"
                a.link v-on:click="setLineuser(lineuser.id)"
                /a.link :href="`/bot/${bot_id}/chat/${lineuser.id}`"
                .user.columns
                  .column.is-3.side-icon
                    img :src="lineuser.pictureUrl" class="post-icon"
                  .column.is-9
                    p = "{{lineuser.name}}"
                    p.about
                      = "{{lineuser.lastmessage.content | truncate(50) }}"

        .form-tab v-show="isActive == 2"
          .users-list
            .users-box
              .user-box v-for="lineuser in lineusers" v-if="lineuser.lastmessage.to_bot == false" v-bind:class="{'is-active': lineuser_id == lineuser.id}"
                /a.link :href="`/bot/${bot_id}/chat/${lineuser.id}`"
                a.link v-on:click="setLineuser(lineuser.id)"
                .user.columns
                  .column.is-3.side-icon
                    img :src="lineuser.pictureUrl" class="post-icon"
                  .column.is-9
                    p = "{{lineuser.name}}"
                    p.about
                      = "{{lineuser.lastmessage.content | truncate(50) }}"
    .column.is-auto.talk-box.content-body
      - if @lineuser
        header.navbar.is-white.is-fixed-top.is-hidden-tablet
          .container
            .navbar-brand
              .navbar-item.is-size-5
                = "{{lineuser.name}}"
                | とのトークルーム
              .navbar-item.float-right
                = link_to '<i class="far fa-arrow-alt-circle-left"></i>'.html_safe, bot_lineusers_path(@bot), class: "is-size-4"
        .header-space.is-hidden-tablet
          p 　
          p 　
          p 　
        .room-bar.is-hidden-mobile
          label.label
            = "{{lineuser.name}}"
            | とのトークルーム
            button.button.float-right v-on:click="detailToggle()"
              i.fas.fa-info-circle
      #messages-box.scroll-message
        messagebox :lineuser="lineuser"
      .message-form
        div v-if="formSwitch == 0"
          textarea name="message" id="message" placeholder="メッセージ" required="required" class="input message-input" v-model="message"
          .inline-block
            div
              button.button.is-info.submit-message name="button" v-on:click="sendMessage()"
                i.far.fa-paper-plane
              div
                button.button type="button" v-on:click="switchForm(1)"
                  i.fas.fa-plus
        div v-if="formSwitch == 1"
          .columns.is-multiline.is-mobile
            .column.is-one-quarter
              button.button.is-size-4 v-on:click="switchForm(0)"
                i.far.fa-comment
            .column.is-one-quarter
              button.button.is-size-4 v-on:click="switchForm(2)"
                i.far.fa-envelope
            / .column.is-one-quarter
              button.button.is-size-4 v-on:click="switchForm(3)"
                i.far.fa-image
            .column.is-one-quarter
              button.button.is-size-4 v-on:click="switchForm(4)"
                i.fas.fa-upload
        div v-if="formSwitch == 2"
          button.button.float-right v-on:click="switchForm(0)"
            i.far.fa-comment
          form data-parsley-validate="" method="post" data-remote="true" v-bind:action="`/bot/${bot_id}/chat/${lineuser.id}/push_flex`" @submit="reloadLineuser"
            input type="hidden" name="authenticity_token" value="#{form_authenticity_token}"
            .select
              = select :quick_reply, :id, @quick_reply_list, {}
            = submit_tag "送信", class: "button is-info inline-block"
        / div v-if="formSwitch == 3"
          button.button.float-right v-on:click="switchForm(0)"
            i.far.fa-comment
          .columns.is-multiline.is-mobile
            - @bot.stock_images&.order(created_at: :desc)&.each do |stock_image|
              .column.is-one-quarter
                = link_to push_image_bot_chat_path(params[:bot_id], params[:lineuser_id], params: { stock_image: { id: stock_image.id } }), data: { confirm: '画像を送信します' }, method: :post do
                  = image_tag stock_image.image.thumb.url, size: '120x120'
        div v-if="formSwitch == 4"
          button.button.float-right v-on:click="switchForm(0)"
            i.far.fa-comment
          form data-parsley-validate="" method="post" data-remote="true" enctype="multipart/form-data" v-bind:action="`/bot/${bot_id}/set_images`" @submit="reloadLineuser"
            input type="hidden" name="authenticity_token" value="#{form_authenticity_token}"
            input type="hidden" name="lineuser[id]" v-bind:value="lineuser.id"
            .file.has-name
              label.file-label
                = file_field_tag "bot[image]", required: "", class: "file-input", id: "file", "v-on:change"=>"changeFileName()"
                span.file-cta
                  span.file-icon
                    i.fas.fa-upload
                  span.file-label Choose a file…
                span.file-name#filename = "{{filename}}"
            = submit_tag "画像を送信", class: "button is-info"



    .column.is-4.overflow v-show="detailShow"
      .label ="{{lineuser.converted ? 'CV済み' : '未CV'}}"
      table.table.is-bordered
        thead
          tr style="white-space: nowrap;"
            th v-for="data in lineuser.response_data"
              = "{{data.quick_reply}}"
        tbody
          tr
            td v-for="data in lineuser.response_data"
              = "{{data.response_text}}"
      form.form data-parsley-validate="" method="post" name="status_form" data-remote="true" v-bind:action="`/lineusers/${lineuser.id}/lineuser_statuses`"
        input type="hidden" name="authenticity_token" value="#{form_authenticity_token}"
        .min-margin
          label.label ステータス
          .field
            p.control
              .select
                select id="page_name" name="bot_lineuser_status[status_id]" v-on:change="submitStatus" v-model="lineuser.status_id"
                  option value="0" 選択してください
                  option v-for="status in statuses" v-bind:value="status.id" {{status.name}}
      .min-margin
        .label スレッド
        .button v-bind:class="lineuser.is_closed ? 'button' : 'button is-success is-outlined'" v-on:click="switchCloseLineuser()"
          = "{{lineuser.is_closed ? 'CLOSED' : 'OPEN'}}"


= javascript_pack_tag "message_show"

app/views/bot/chat/top.html.erb
<p>linebot</p>
<div class="container">
  <div class="columns">
    <div class="column is-3">
      <div class="users-list">
        <div class="users-box">
          <% @userslist.each_with_index do |user, index|%>
            <div class="user-box">
              <%= link_to "", "/chat/#{user.id}", class: "link" %>
              <div class="user">
                <p><%= user.name %></p>
                <p class="about">
                  <% if @last_messages[index] %>
                    <%= @last_messages[index].content %>
                  <% else %>

                  <% end %>
                </p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="column is-9">
      <p><%= @users[:lineuser].name %> とのトークルーム</p>
      <div class="messages-box">
        <% @messages.each do |message|%>
          <div class="message-box">
            <%if message.user_id == "U72798cffe98b02650a359df76ca76b36"%>
              <div class="message user-side">
                <p><%= @users[:lineuser].name %>　｜　<%= message.content %></p>
              </div>
            <% elsif message.user_id == "1" %>
              <div class="message bot-side">
                <p><%= @users[:bot].name %>　｜　<%= message.content %></p>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>
      <%= link_to "テスト送信", "/chat/test_push", class: "button is-primary", method: :post %>
      <%= form_tag "/chat/push", method: :post do %>
          <%= text_field_tag :message, "", placeholder: "メッセージ", class: "input" %>
          <%= submit_tag "送信", class: "button is-info" %>
      <% end %>
    </div>
  </div>
</div>